[worker]
start = 1716560632750
step = 18000000
request_interval = 1000

[worker.strategy]
name = "parallel"
workers = 10

[server]
port = "8080"

[backfill]
name = "backfill-1"
start = 1716560632750
end = 1716560632750
request_interval = 1000

[processors.lending]
name = "lending"
contract_address = "yuF1Sum4ricLFBc86h3RdjFsebR7ZXKBHm2S5sZmVsiF"
