x-logging: &default-logging
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"

services:
  db:
    image: postgres:17
    <<: *default-logging
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-bento_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-bento_password}
      POSTGRES_DB: ${POSTGRES_DB:-bento_db}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-bento_user} -d ${POSTGRES_DB:-bento_db}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bento-network
    labels:
      - "traefik.enable=false"

  indexer:
    image: linx-app-backend/indexer:${VERSION:-1.0.0}
    build:
      context: .
      dockerfile: Dockerfile
    <<: *default-logging
    command: /app/cli run worker
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./examples/linx-indexer/config.toml:/app/config.toml
    networks:
      - bento-network
    labels:
      - "traefik.enable=false"

  api:
    image: linx-app-backend/api:${VERSION:-1.0.0}
    build:
      context: .
      dockerfile: Dockerfile
    <<: *default-logging
    command: /app/cli run server
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./examples/linx-indexer/config.toml:/app/config.toml
    networks:
      - bento-network
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.linx-app-api.rule=Host(`api.linxlabs.org`) && (PathPrefix(`/history`) || PathPrefix(`/lending`) || PathPrefix(`/points`))"
      - "traefik.http.routers.linx-app-api.entrypoints=websecure"
      - "traefik.http.services.linx-app-api.loadbalancer.server.port=8080"
      - "traefik.http.routers.linx-app-api.tls.certresolver=cfresolver"
      - "traefik.http.routers.linx-app-api.service=linx-app-api"

  cli:
    image: linx-app-backend/cli:${VERSION:-1.0.0}
    build:
      context: .
      dockerfile: Dockerfile.cli
    <<: *default-logging
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./examples/linx-indexer/config.toml:/app/config.toml
      - ./examples/linx-indexer/migrations:/app/migrations
      - ./examples/linx-indexer/src/schema.rs:/app/src/schema.rs
    networks:
      - bento-network
    labels:
      - "traefik.enable=false"

networks:
  bento-network:
  traefik:
    external: true
    name: traefik

volumes:
  postgres_data:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/volume_linx_app_backend/postgres-data/
      o: bind
