[worker]
request_interval = 5000
step = 10000
backstep = 30000

[backfill]
workers = 2
request_interval = 100 # 5 seconds
step = 30000
backstep = 30000       # 1 minute backstep

[server]

[points]
referral_percentage = 0.05
signup_bonus = 1000
calculation_time = "01:00" # Time in HH:MM format (24-hour) for daily scheduler
